@url = http://localhost:8080/api/user

### return All -
GET {{url}} HTTP/1.1

### return Feedback -
GET {{url}}/dffec086-b1e9-455a-aab4-ff6c6611fef0/feedback-tag HTTP/1.1

###
GET {{url}}/username/accepter101 HTTP/1.1

###
GET {{url}}/id/25821ab3-6e6c-4258-911f-177ae9e13b31 HTTP/1.1

### should not add crappy password. 
POST {{url}}/create-account HTTP/1.1
Content-Type: application/json

{
    "email": "Testemail@gmail.com",
    "password": "crapass",
    "username": "badPasswordGuy",
    "photoUrl": null,
    "country": "United States",
    "bio": null
}

### should not add short password. 
POST {{url}}/create-account HTTP/1.1
Content-Type: application/json

{
    "email": "Testemail@gmail.com",
    "password": "sh0R7#",
    "username": "shortPasswordGuy",
    "photoUrl": null,
    "country": "United States",
    "bio": null
}

### should post 
POST {{url}}/create-account HTTP/1.1
Content-Type: application/json

{
    "email": "milanstoj94@gmail.com",
    "password": "P4$$word",
    "username": "miro-stoj",
    "photoUrl": null,
    "country": "United States",
    "bio": null
}

### should Edit 204 No content
PUT {{url}}/0e4e4bcb-0477-41c1-9ff5-000a7d62b032  HTTP/1.1
Content-Type: application/json

{
    "userId": "0e4e4bcb-0477-41c1-9ff5-000a7d62b032",
    "username": "milan-stoj",
    "role": "controller",
    "photoUrl": null,
    "country": "United States",
    "bio": "hello, world!"
}


### should Delete 204 no content 
DELETE {{url}}/0e4e4bcb-0477-41c1-9ff5-000a7d62b032  HTTP/1.1

###

GET {{url}}/logged-in-user HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJkaXNzZW50Iiwic3ViIjoiYWRtaW4iLCJhdXRob3JpdGllcyI6IlJPTEVfQURNSU4sUk9MRV9VU0VSIiwidXNlcklkIjoiZGZmZWMwODYtYjFlOS00NTVhLWFhYjQtZmY2YzY2MTFmZWYwIiwiZXhwIjoxNjE0MTg1Mzk5fQ.mDk_DCEnNAWYmpFKQ5oWp-j88Oq4QTCYuZtjMkAmuzw